services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: sql_server
    environment:
      MSSQL_SA_PASSWORD: "Jakarta@202608"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: